services:
  web:
    build: .
    container_name: cuckoo_pump_web
    restart: always
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: cuckoo_pump_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cuckoo}
    volumes:
      - pg_data:/var/lib/postgresql/data

  gateway:
    build: ./gateway
    container_name: cuckoo_pump_gateway
    restart: always
    ports:
      - "8000:80"   # наружу отдаём только nginx
    depends_on:
      - web
  bot:
    build: .
    container_name: cuckoo_pump_bot
    restart: always
    env_file:
      - .env
    command: python tg_bot.py
    depends_on:
      - web

volumes:
  pg_data:
