services:
  db:
    image: postgres:14
    container_name: cuckoo_pump_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cuckoo}
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    image: ndk985/cuckoo_pump-web:latest
    container_name: cuckoo_pump_web
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"  # Публикуем на localhost для доступа бота (network_mode: host)
    depends_on:
      - db
    volumes:
      - instance_data:/app/instance

  gateway:
    image: ndk985/cuckoo_pump-gateway:latest
    container_name: cuckoo_pump_gateway
    restart: always
    ports:
      - "8080:80"   # наружу отдаём только nginx
    depends_on:
      - web
  bot:
    image: ndk985/cuckoo_pump-web:latest
    container_name: cuckoo_pump_bot
    restart: always
    env_file:
      - .env
    command: python tg_bot.py
    # Используем сеть хоста для обхода SSL-инспекции Docker сети
    network_mode: host
    # Бот подключается к web через localhost:8000
    environment:
      - FLASK_HOST=http://localhost:8000

volumes:
  pg_data:
  instance_data:
